Fixing Error Received When First Validator is a Custom Presence Validator
    Received <NoMethodError: undefined method 'any?' for nil:NilClass> when
    validating with a presence validator before a type validator was
    defined. This was because the reduction within the type validators did
    not return the collection on 'next'.